sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - COMPOSER_ARGS="--no-interaction"

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env:
        - DEPS=lowest
    - php: 7.2
      env:
        - DEPS=latest
        - TEST_COVERAGE=true
    - php: 7.2
      env:
        - DEPS=dev
    - php: 7.3
      env:
        - DEPS=latest
    - php: 7.4
      env:
        - DEPS=latest
    - php: 8.0
      env:
        - DEPS=latest

before_install:
  - travis_retry composer self-update

install:
  - if [[ $DEPS == 'dev' ]]; then travis_retry composer config minimum-stability dev ; fi
  - if [[ $DEPS == 'latest' || $DEPS == 'dev' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - travis_retry composer install $COMPOSER_ARGS
  - composer show

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; else composer test ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then php build/coverage-checker.php build/clover.xml 70 ; fi

after_success:
  - if [[ $TEST_COVERAGE == 'true' ]]; then bash <(curl -s https://codecov.io/bash) -f ./build/clover.xml; fi
